spring.application.name=hotelhub
spring.datasource.url=jdbc:postgresql://localhost:5433/hotelHub
spring.datasource.username=postgres
spring.datasource.password=1234
logging.file.name=logs/hotelhub.log
logging.level.com.example.hotelhub=info

spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ için
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.listener.simple.auto-startup=false
spring.elasticsearch.uris=http://localhost:9200

management.endpoints.web.exposure.include=health,info,prometheus

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.cookie.secure=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
management.server.port=8080

# Rate Limiting Configuration (Redis tabanlı)
# Bir IP adresinin pencere süresi içinde yapabileceği maksimum istek sayısı
rate.limit.requests=50
# Pencere süresi (saniye cinsinden) - Bu süre dolduğunda sayaç sıfırlanır
rate.limit.window-seconds=60
